//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalTrace.Language.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalTrace.Language.Localization.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Limpar.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copiar.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantidade de entradas:.
        /// </summary>
        internal static string countall {
            get {
                return ResourceManager.GetString("countall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diretórios:.
        /// </summary>
        internal static string countdirectories {
            get {
                return ResourceManager.GetString("countdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arquivos:.
        /// </summary>
        internal static string countfiles {
            get {
                return ResourceManager.GetString("countfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entrada mais antiga:.
        /// </summary>
        internal static string countfirst {
            get {
                return ResourceManager.GetString("countfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arquivo atual.
        /// </summary>
        internal static string currentfile {
            get {
                return ResourceManager.GetString("currentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grade de dados.
        /// </summary>
        internal static string datagrid {
            get {
                return ResourceManager.GetString("datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diretório.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arvore de diretórios.
        /// </summary>
        internal static string directorytree {
            get {
                return ResourceManager.GetString("directorytree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disco.
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entrar no diretório da entrada.
        /// </summary>
        internal static string enterdir {
            get {
                return ResourceManager.GetString("enterdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mostrar informações do arquivo.
        /// </summary>
        internal static string entryinfo {
            get {
                return ResourceManager.GetString("entryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exportar.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arquivo.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arquivo foi deletado.
        /// </summary>
        internal static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identificador do arquivo.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formato.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seleção de disco.
        /// </summary>
        internal static string formdrive {
            get {
                return ResourceManager.GetString("formdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Informações da entrada.
        /// </summary>
        internal static string formentryinfo {
            get {
                return ResourceManager.GetString("formentryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Informação.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lingua.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ideia para o projeto, traduziu razões.
        /// </summary>
        internal static string lordyzagatdesc {
            get {
                return ResourceManager.GetString("lordyzagatdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OpenByFileId Win32 API compatibilização para C#.
        /// </summary>
        internal static string nolandesc {
            get {
                return ResourceManager.GetString("nolandesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desenvolvedor principal.
        /// </summary>
        internal static string poneidesc {
            get {
                return ResourceManager.GetString("poneidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Razão.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raiz.
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Escanear.
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pesquisar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selecionar.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NTFS UsnJournal Win32 API compatibilização para C#.
        /// </summary>
        internal static string skipperdesc {
            get {
                return ResourceManager.GetString("skipperdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O programa não conseguiu manejar o disco selecionado, para consultar o estado atual do journal..
        /// </summary>
        internal static string statusdesc_1 {
            get {
                return ResourceManager.GetString("statusdesc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O programa não conseguiu consultar o estado atual do journal. Certifique-se de que o disco selecionado tenha o journal habilitado..
        /// </summary>
        internal static string statusdesc_2 {
            get {
                return ResourceManager.GetString("statusdesc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O programa não conseguiu chamar o DeviceIoControl corretamente para retornar todos as entradas do journal do disco..
        /// </summary>
        internal static string statusdesc_3 {
            get {
                return ResourceManager.GetString("statusdesc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O programa não conseguiu resolver as identificações dos arquivos corretamente. Algo está bloqueando o programa?.
        /// </summary>
        internal static string statusdesc_4 {
            get {
                return ResourceManager.GetString("statusdesc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O programa não conseguiu analisar corretamente as entradas do journal corretamente. Isto pode ser culpa do programa..
        /// </summary>
        internal static string statusdesc_5 {
            get {
                return ResourceManager.GetString("statusdesc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Por favor, selecione o disco desejado e incie a filtragem do journal..
        /// </summary>
        internal static string statusdesc0 {
            get {
                return ResourceManager.GetString("statusdesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Para consultar o journal, temos que ter certeza de que podemos criar handles sem problemas..
        /// </summary>
        internal static string statusdesc1 {
            get {
                return ResourceManager.GetString("statusdesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Precisamos consultar o estado atual do journal para obter seus valores..
        /// </summary>
        internal static string statusdesc2 {
            get {
                return ResourceManager.GetString("statusdesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chamando de DeviceIoControl para nos dar todas as entradas do ID do journal atual..
        /// </summary>
        internal static string statusdesc3 {
            get {
                return ResourceManager.GetString("statusdesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Os ID&apos;s dos arquivos não são caminhos legíveis por humanos, então precisamos resolver todos os possíveis..
        /// </summary>
        internal static string statusdesc4 {
            get {
                return ResourceManager.GetString("statusdesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformando todas as entradas de journal em classes que modificaremos e consultaremos mais tarde..
        /// </summary>
        internal static string statusdesc5 {
            get {
                return ResourceManager.GetString("statusdesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selecione um tipo de layout para visualizar os dados coletados. Cada um mostrará os dados de uma maneira diferente..
        /// </summary>
        internal static string statusdesc6 {
            get {
                return ResourceManager.GetString("statusdesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformando entradas em fileiras....
        /// </summary>
        internal static string statusgrid0 {
            get {
                return ResourceManager.GetString("statusgrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adicionando fileiras à grade....
        /// </summary>
        internal static string statusgrid1 {
            get {
                return ResourceManager.GetString("statusgrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Não foi possível manejar o disco selecionado..
        /// </summary>
        internal static string statustitle_1 {
            get {
                return ResourceManager.GetString("statustitle-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Não foi possível retornar o estado atual do journal..
        /// </summary>
        internal static string statustitle_2 {
            get {
                return ResourceManager.GetString("statustitle-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Não foi possível consultar as entradas do journal..
        /// </summary>
        internal static string statustitle_3 {
            get {
                return ResourceManager.GetString("statustitle-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Não foi possível resolver os ID&apos;s..
        /// </summary>
        internal static string statustitle_4 {
            get {
                return ResourceManager.GetString("statustitle-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Não foi possível analisar as entradas..
        /// </summary>
        internal static string statustitle_5 {
            get {
                return ResourceManager.GetString("statustitle-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aguardando entrada....
        /// </summary>
        internal static string statustitle0 {
            get {
                return ResourceManager.GetString("statustitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting handle to volume....
        /// </summary>
        internal static string statustitle1 {
            get {
                return ResourceManager.GetString("statustitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obtendo o estado atual do journal....
        /// </summary>
        internal static string statustitle2 {
            get {
                return ResourceManager.GetString("statustitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consultando as entradas do journal....
        /// </summary>
        internal static string statustitle3 {
            get {
                return ResourceManager.GetString("statustitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolvendo identificações de arquivos....
        /// </summary>
        internal static string statustitle4 {
            get {
                return ResourceManager.GetString("statustitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analisando entradas....
        /// </summary>
        internal static string statustitle5 {
            get {
                return ResourceManager.GetString("statustitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tudo pronto!.
        /// </summary>
        internal static string statustitle6 {
            get {
                return ResourceManager.GetString("statustitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Espaço total livre.
        /// </summary>
        internal static string totalfreespace {
            get {
                return ResourceManager.GetString("totalfreespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Espaço total.
        /// </summary>
        internal static string totalsize {
            get {
                return ResourceManager.GetString("totalsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tipo.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Substituição de dados,Extensão de dados,Truncagem de dados,Substituição de dados nomeados,Extensão de dados nomeados,Truncagem de dados nomeados,Criação de arquivo,Exclusão de arquivo,Alteração de EA,Alteração de segurança,Renomear: nome antigo,Renomear: novo nome,Alteração de indexável,Alteração de informações básicas,Alteração de link físico,Alteração de compressão,Alteração de criptografia,Alteração de ID de objeto,Alteração do ponto de nova análise,Alteração de fluxo,Fechar.
        /// </summary>
        internal static string usnreasons {
            get {
                return ResourceManager.GetString("usnreasons", resourceCulture);
            }
        }
    }
}
